drop view if exists public.jgali3_assignment_flattern_v;
create or replace view public.jgali3_assignment_flattern_v as
select
	sample_data::json ->> 'id'::text as id,
	sample_data::json ->> 'email'::text as email,
	sample_data::json ->> 'closed_at'::text as closed_at,
	sample_data::json ->> 'created_at'::text as created_at,
	sample_data::json ->> 'updated_at'::text as updated_at,
	sample_data::json ->> 'number'::text as number,
	sample_data::json ->> 'note'::text as note,
	sample_data::json ->> 'token'::text as token,
	sample_data::json ->> 'gateway'::text as gateway,
	sample_data::json ->> 'test'::text as test,
	sample_data::json ->> 'total_price'::text as total_price,
	sample_data::json ->> 'subtotal_price'::text as subtotal_price,
	sample_data::json ->> 'total_weight'::text as total_weight,
	sample_data::json ->> 'total_tax'::text as total_tax,
	sample_data::json ->> 'taxes_included'::text as taxes_included,
	sample_data::json ->> 'currency'::text as currency,
	sample_data::json ->> 'financial_status'::text as financial_status,
	sample_data::json ->> 'confirmed'::text as confirmed,
	sample_data::json ->> 'total_discounts'::text as total_discounts,
	sample_data::json ->> 'cart_token'::text as cart_token,
	sample_data::json ->> 'buyer_accepts_marketing'::text as buyer_accepts_marketing,
	sample_data::json ->> 'name'::text as name,
	sample_data::json ->> 'referring_site'::text as referring_site,
	sample_data::json ->> 'landing_site'::text as landing_site,
	sample_data::json ->> 'cancelled_at'::text as cancelled_at,
	sample_data::json ->> 'cancel_reason'::text as cancel_reason,
	sample_data::json ->> 'total_price_usd'::text as total_price_usd,
	sample_data::json ->> 'checkout_token'::text as checkout_token,
	sample_data::json ->> 'reference'::text as reference,
	sample_data::json ->> 'user_id'::text as user_id,
	sample_data::json ->> 'location_id'::text as location_id,
	sample_data::json ->> 'source_identifier'::text as source_identifier,
	sample_data::json ->> 'source_url'::text as source_url,
	sample_data::json ->> 'processed_at'::text as processed_at,
	sample_data::json ->> 'device_id'::text as device_id,
	sample_data::json ->> 'phone'::text as phone,
	sample_data::json ->> 'customer_locale'::text as customer_locale,
	sample_data::json ->> 'app_id'::text as app_id,
	sample_data::json ->> 'browser_ip'::text as browser_ip,
	sample_data::json ->> 'landing_site_ref'::text as landing_site_ref,
	sample_data::json ->> 'order_number'::text as order_number,
	sample_data::json ->> 'processing_method'::text as processing_method,
	sample_data::json ->> 'checkout_id'::text as checkout_id,
	sample_data::json ->> 'source_name'::text as source_name,
	sample_data::json ->> 'fulfillment_status'::text as fulfillment_status,
	sample_data::json ->> 'tags'::text as tags,
	sample_data::json ->> 'contact_email'::text as contact_email,
	sample_data::json ->> 'order_status_url'::text as order_status_url,
	sample_data::json ->> 'line_items'::text as line_items,
  	sample_data::json ->> 'total_discount'::text as total_discount,
	load_timestamp as load_timestamp
from
	public.jgali3_assignment;
   
